src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PromotionRepository::class)]
class Promotion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\ManyToOne(targetEntity: Formation::class, inversedBy: 'promotion')]
    #[ORM\JoinColumn(nullable: false)]
    private $formation;

    #[ORM\OneToMany(mappedBy: 'promotion', targetEntity: Candidat::class)]
    private $candidats;

    #[ORM\ManyToOne(targetEntity: Formateur::class)]
    #[ORM\JoinColumn(nullable: false)]
    private $formateur_referent;

    #[ORM\OneToMany(mappedBy: 'promotion', targetEntity: Session::class)]
    private $sessions;

    public function __construct()
    {
        $this->candidats = new ArrayCollection();
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    /**
     * @return Collection<int, Candidat>
     */
    public function getCandidats(): Collection
    {
        return $this->candidats;
    }

    public function addCandidat(Candidat $candidat): self
    {
        if (!$this->candidats->contains($candidat)) {
            $this->candidats[] = $candidat;
            $candidat->setPromotion($this);
        }

        return $this;
    }

    public function removeCandidat(Candidat $candidat): self
    {
        if ($this->candidats->removeElement($candidat)) {
            // set the owning side to null (unless already changed)
            if ($candidat->getPromotion() === $this) {
                $candidat->setPromotion(null);
            }
        }

        return $this;
    }

    public function getFormateurReferent(): ?Formateur
    {
        return $this->formateur_referent;
    }

    public function setFormateurReferent(?Formateur $formateur_referent): self
    {
        $this->formateur_referent = $formateur_referent;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->setPromotion($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getPromotion() === $this) {
                $session->setPromotion(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $date_debut;

    #[ORM\Column(type: 'date')]
    private $date_fin;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\ManyToOne(targetEntity: Promotion::class, inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private $promotion;

    #[ORM\ManyToMany(targetEntity: Formateur::class, inversedBy: 'sessions')]
    private $formateurs;

    #[ORM\ManyToMany(targetEntity: Salle::class, inversedBy: 'sessions')]
    private $salle;

    public function __construct()
    {
        $this->formateurs = new ArrayCollection();
        $this->salle = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPromotion(): ?Promotion
    {
        return $this->promotion;
    }

    public function setPromotion(?Promotion $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    /**
     * @return Collection<int, Formateur>
     */
    public function getFormateurs(): Collection
    {
        return $this->formateurs;
    }

    public function addFormateur(Formateur $formateur): self
    {
        if (!$this->formateurs->contains($formateur)) {
            $this->formateurs[] = $formateur;
        }

        return $this;
    }

    public function removeFormateur(Formateur $formateur): self
    {
        $this->formateurs->removeElement($formateur);

        return $this;
    }

    /**
     * @return Collection<int, Salle>
     */
    public function getSalle(): Collection
    {
        return $this->salle;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salle->contains($salle)) {
            $this->salle[] = $salle;
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        $this->salle->removeElement($salle);

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('formation')
            ->add('formateur_referent')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/promotion')]
class PromotionController extends AbstractController
{
    #[Route('/', name: 'app_promotion_index', methods: ['GET'])]
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_promotion_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PromotionRepository $promotionRepository): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotionRepository->add($promotion, true);

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_show', methods: ['GET'])]
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_promotion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Promotion $promotion, PromotionRepository $promotionRepository): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotionRepository->add($promotion, true);

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_delete', methods: ['POST'])]
    public function delete(Request $request, Promotion $promotion, PromotionRepository $promotionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->request->get('_token'))) {
            $promotionRepository->remove($promotion, true);
        }

        return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('app_promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/promotion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <thead>
	<tr>
		<th>
			{{ block("newFormationButton", 'buttons.html.twig') }}
		</th>
		<th>
			{{ block("newFormateurButton", 'buttons.html.twig') }}
		</th>
	</tr>
</thead>
<div>
	<button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
</div>
{{ form_end(form) }}

templates/promotion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Promotion{% endblock %}

{% block body %}
    <h1>Edit Promotion</h1>

    {{ include('promotion/_form.html.twig', {'button_label': 'Update'}) }}

    <a class='btn btn-primary' role='button' href="{{ path('app_promotion_index') }}">back to list</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion index{% endblock %}

{% block body %}
    <h1>Promotion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Nombre Candidats</th>
                <th>Formateur référent</th>
                <th>Sessions restantes</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.nom }}</td>
                <td>{{ promotion.candidats | length }}</td>
                <td>{{ promotion.formateurReferent }}</td>
                <td>{{ promotion.sessions | length }}</td>
                <td>
                    <a class='btn btn-primary' role='button' href="{{ path('app_promotion_show', {'id': promotion.id}) }}">Détails</a>
                    <a class='btn btn-primary' role='button' href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class='btn btn-primary' role='button' href="{{ path('app_promotion_new') }}">Nouveau</a>
{% endblock %}

templates/promotion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promotion{% endblock %}

{% block body %}
    <h1>Nouvelle Promotion</h1>

    {{ include('promotion/_form.html.twig') }}

    <a class='btn btn-primary' role='button' href="{{ path('app_promotion_index') }}">Retour</a>
{% endblock %}

templates/promotion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion
{% endblock %}

{% block body %}
	<h1>Promotion</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ promotion.id }}</td>
			</tr>
			<tr>
				<th>Nom</th>
				<td>{{ promotion.nom }}</td>
			</tr>
			<tr>
				<th>Sessions à venir</th>
				<td>
					<ul>
						{% for session in promotion.sessions %}
							{% if session.dateDebut > date('now') %}
								<li>
									<a href="\" "{{ path('app_session_show', { 'id': session.id }) }}\">
										{{ session.nom }}
									</a>
								</li>
							{% endif %}
						{% else %}
							<li>
								Aucune session à venir
							</li>
						{% endfor %}
					</ul>
				</td>
			</tr>
			<tr>
				<th>Sessions passées</th>
				<td>
					<ul>
						{% for session in promotion.sessions %}
							{% if session.dateDebut < date('now') %}
								<li>
									<a href="\" "{{ path('app_session_show', { 'id': session.id }) }}\">
										{{ session.nom }}
									</a>
								</li>
							{% endif %}
						{% else %}
							<li>
								Aucune session passée
							</li>
						{% endfor %}
					</ul>
				</td>
			</tr>
		</tbody>
	</table>

	<a class='btn btn-primary' role='button' href="{{ path('app_promotion_index') }}">back to list</a>

	<a class='btn btn-primary' role='button' href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>

	{{ include('promotion/_delete_form.html.twig') }}
{% endblock %}