src/Entity/Formateur.php
<?php

namespace App\Entity;

use App\Repository\FormateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormateurRepository::class)]
class Formateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\Column(type: 'string', length: 255)]
    private $mail;

    #[ORM\Column(type: 'string', length: 255)]
    private $tel;

    #[ORM\ManyToMany(targetEntity: Session::class, mappedBy: 'formateurs')]
    private $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->addFormateur($this);
        }

        return $this;
    }

    public function removeSession(Session $session): self
    {
        if ($this->sessions->removeElement($session)) {
            $session->removeFormateur($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getNom() . " " . $this->getPrenom();
    }
}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $date_debut;

    #[ORM\Column(type: 'date')]
    private $date_fin;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\ManyToOne(targetEntity: Promotion::class, inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private $promotion;

    #[ORM\ManyToMany(targetEntity: Formateur::class, inversedBy: 'sessions')]
    private $formateurs;

    #[ORM\ManyToMany(targetEntity: Salle::class, inversedBy: 'sessions')]
    private $salle;

    public function __construct()
    {
        $this->formateurs = new ArrayCollection();
        $this->salle = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPromotion(): ?Promotion
    {
        return $this->promotion;
    }

    public function setPromotion(?Promotion $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    /**
     * @return Collection<int, Formateur>
     */
    public function getFormateurs(): Collection
    {
        return $this->formateurs;
    }

    public function addFormateur(Formateur $formateur): self
    {
        if (!$this->formateurs->contains($formateur)) {
            $this->formateurs[] = $formateur;
        }

        return $this;
    }

    public function removeFormateur(Formateur $formateur): self
    {
        $this->formateurs->removeElement($formateur);

        return $this;
    }

    /**
     * @return Collection<int, Salle>
     */
    public function getSalle(): Collection
    {
        return $this->salle;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salle->contains($salle)) {
            $this->salle[] = $salle;
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        $this->salle->removeElement($salle);

        return $this;
    }

    public function __toString()
    {
        return $this->getNom();
    }
}

src/Form/FormateurType.php
<?php

namespace App\Form;

use App\Entity\Formateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('mail')
            ->add('tel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formateur::class,
        ]);
    }
}

src/Controller/FormateurController.php
<?php

namespace App\Controller;

use App\Entity\Formateur;
use App\Form\FormateurType;
use App\Repository\FormateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/formateur')]
class FormateurController extends AbstractController
{
    #[Route('/', name: 'app_formateur_index', methods: ['GET'])]
    public function index(FormateurRepository $formateurRepository): Response
    {
        return $this->render('formateur/index.html.twig', [
            'formateurs' => $formateurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_formateur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FormateurRepository $formateurRepository): Response
    {
        $formateur = new Formateur();
        $form = $this->createForm(FormateurType::class, $formateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formateurRepository->add($formateur, true);

            return $this->redirectToRoute('app_formateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formateur/new.html.twig', [
            'formateur' => $formateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formateur_show', methods: ['GET'])]
    public function show(Formateur $formateur): Response
    {
        return $this->render('formateur/show.html.twig', [
            'formateur' => $formateur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_formateur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Formateur $formateur, FormateurRepository $formateurRepository): Response
    {
        $form = $this->createForm(FormateurType::class, $formateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $formateurRepository->add($formateur, true);

            return $this->redirectToRoute('app_formateur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('formateur/edit.html.twig', [
            'formateur' => $formateur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_formateur_delete', methods: ['POST'])]
    public function delete(Request $request, Formateur $formateur, FormateurRepository $formateurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formateur->getId(), $request->request->get('_token'))) {
            $formateurRepository->remove($formateur, true);
        }

        return $this->redirectToRoute('app_formateur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/formateur/_delete_form.html.twig
<form method="post" action="{{ path('app_formateur_delete', {'id': formateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formateur.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/formateur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/formateur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Formateur{% endblock %}

{% block body %}
    <h1>Modifier Formateur</h1>

    {{ include('formateur/_form.html.twig', {'button_label': 'Update'}) }}

    <a class='btn btn-primary' role='button' href="{{ path('app_formateur_index') }}">Retour</a>

    {{ include('formateur/_delete_form.html.twig') }}
{% endblock %}

templates/formateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formateur index{% endblock %}

{% block body %}
    <h1>Formateurs</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Mail</th>
                <th>Tel</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for formateur in formateurs %}
            <tr>
                <td>{{ formateur.nom }}</td>
                <td>{{ formateur.prenom }}</td>
                <td>{{ formateur.mail }}</td>
                <td>{{ formateur.tel }}</td>
                <td>
                    <a class='btn btn-primary' role='button' href="{{ path('app_formateur_show', {'id': formateur.id}) }}">Détails</a>
                    <a class='btn btn-primary' role='button' href="{{ path('app_formateur_edit', {'id': formateur.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class='btn btn-primary' role='button' href="{{ path('app_formateur_new') }}">Nouveau</a>
{% endblock %}

templates/formateur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formateur{% endblock %}

{% block body %}
    <h1>Nouveau Formateur</h1>

    {{ include('formateur/_form.html.twig') }}

    <a class='btn btn-primary' role='button' href="{{ path('app_formateur_index') }}">Retour</a>
{% endblock %}

templates/formateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formateur{% endblock %}

{% block body %}
    <h1>Formateur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ formateur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ formateur.prenom }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ formateur.mail }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ formateur.tel }}</td>
            </tr>
            <tr>
                <th>Sessions à venir</th>
                <td>
                    <ul>
                        {% for session in formateur.sessions %}
                            {% if session.dateFin > date("now") %}
                            <li>
                            <a href={{ url('app_session_show', {id: session.id} )}}>
                            {{ session.nom }} : {{session.dateDebut | date('d/m/y')}} au {{session.dateFin | date('d/m/y')}}
                            </a>
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>

    <a class='btn btn-primary' role='button' href="{{ path('app_formateur_index') }}">Retour</a>

    <a class='btn btn-primary' role='button' href="{{ path('app_formateur_edit', {'id': formateur.id}) }}">Modifier</a>

    {{ include('formateur/_delete_form.html.twig') }}
{% endblock %}